"""Custom Sales Invoice override for POS Awesome."""

from __future__ import annotations

from decimal import Decimal, getcontext

import frappe
from frappe import _
from frappe.utils import flt

from erpnext.accounts.doctype.sales_invoice.sales_invoice import (
    SalesInvoice as ERPNextSalesInvoice,
)


class CustomSalesInvoice(ERPNextSalesInvoice):
    """Override ERPNext Sales Invoice to enforce stricter POS validation."""

    def validate_pos(self):
        """Ensure paid total never exceeds the invoice total on returns.

        The check is skipped for regular invoices and for consolidated
        invoices generated by the POS closing process.
        """

        # Only run check for return invoices, not for system-generated consolidated invoices
        if not getattr(self, "is_return", 0):
            return

        # If this invoice was generated by POS consolidation, skip check
        if getattr(self, "is_consolidated", 0):
            return

        invoice_total_value = (
            self.rounded_total if self.rounded_total not in (None, "") else self.grand_total
        )

        try:
            precision_total = int(self.precision("grand_total") or 2)
        except Exception:
            precision_total = 2

        getcontext().prec = max(28, precision_total + 10)

        def to_decimal(val):
            return Decimal(str(flt(val or 0.0)))

        invoice_total = to_decimal(invoice_total_value)
        paid_amount = to_decimal(abs(self.paid_amount))
        write_off_amount = to_decimal(abs(self.write_off_amount))

        tolerance = Decimal(1) / (Decimal(10) ** Decimal(precision_total + 1))

        diff = paid_amount + write_off_amount - abs(invoice_total)

        if diff > tolerance:
            frappe.throw(_("Paid amount + Write Off Amount can not be greater than Grand Total"))
